In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

In [19]:
faulty_path = Path('..', 'Dataset', 'pre-processed', '402_faulty', 'processed_402_R_faulty.csv')
faulty_path.exists()

True

In [20]:
df = pd.read_csv(faulty_path)

In [21]:
df['phase'] = 'R'
df['breaker_id'] = 402

In [22]:
df.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH5 Close-Velocity (m/s),CH5 Open-Velocity (m/s),CH5 Test Run,DCRM Res CH6 in uOhm,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,phase,breaker_id
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0,0.12,TR4,368.25,0,0,0.12,TR4,R,402
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0,0.12,TR4,379.98,0,0,0.12,TR4,R,402
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0,0.12,TR4,378.02,0,0,0.12,TR4,R,402
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0,0.12,TR4,393.65,0,0,0.12,TR4,R,402
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0,0.12,TR4,393.65,0,0,0.12,TR4,R,402

In [23]:
other = Path('..', 'Dataset', 'processed_402_R_faulty.csv')
other.exists()

True

In [24]:
df1 = pd.read_csv(other)

In [25]:
df1.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN

In [26]:
df1['phase'] = df['phase']
df1['breaker_id'] = df['breaker_id']

In [27]:
df1.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break,phase,breaker_id
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402

In [28]:
df1.to_csv(other, index=False)

In [29]:
df1 = pd.read_csv(other)

In [30]:
df1.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break,phase,breaker_id
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,R,402

In [37]:
df1.columns

Index(['Coil Current C1 (A)', 'Coil Current C2 (A)', 'Coil Current C3 (A)',
       'Coil Current C4 (A)', 'Coil Current C5 (A)', 'Coil Current C6 (A)',
       'Contact Travel T1 (mm)', 'Contact Travel T2 (mm)',
       'Contact Travel T3 (mm)', 'Contact Travel T4 (mm)',
       'Contact Travel T5 (mm)', 'Contact Travel T6 (mm)',
       'DCRM Res CH1 in uOhm', 'DCRM Current CH1 in Amp',
       'CH1 Close-Velocity (m/s)', 'CH1 Open-Velocity (m/s)', 'CH1 Test Run',
       'DCRM Res CH2 in uOhm', 'DCRM Current CH2 in Amp',
       'CH2 Close-Velocity (m/s)', 'CH2 Open-Velocity (m/s)', 'CH2 Test Run',
       'DCRM Res CH3 in uOhm', 'DCRM Current CH3 in Amp',
       'CH3 Close-Velocity (m/s)', 'CH3 Open-Velocity (m/s)', 'CH3 Test Run',
       'CH3 Resistance Break', 'DCRM Res CH4 in uOhm',
       'DCRM Current CH4 in Amp', 'CH4 Close-Velocity (m/s)',
       'CH4 Open-Velocity (m/s)', 'CH4 Test Run', 'CH4 Resistance Break',
       'DCRM Res CH5 in uOhm', 'DCRM Current CH5 in Amp',
       'CH5 Close-Velocity (m/s)', 'CH5 Open-Velocity (m/s)', 'CH5 Test Run',
       'DCRM Res CH6 in uOhm', 'DCRM Current CH6 in Amp',
       'CH6 Close-Velocity (m/s)', 'CH6 Open-Velocity (m/s)', 'CH6 Test Run',
       'CH3 Bounce Break', 'CH4 Bounce Break', 'CH1 Resistance Break',
       'CH2 Resistance Break', 'CH1 Bounce Break', 'CH2 Bounce Break', 'phase',
       'breaker_id'],
      dtype='str')

In [44]:
df1.drop(['phase', 'breaker_id'], axis=1, inplace=True)

KeyError: "['phase', 'breaker_id'] not found in axis"

In [45]:
df1.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN

In [46]:
i = 0
for col in df1.columns:
    if col == 'CH6 Test Run':
        break
    i += 1
i

43

In [49]:
df1.columns[43]

'CH6 Test Run'

In [50]:
df1.insert(44, 'phase', 'R')

In [51]:
df1.insert(45, 'breaker_id', 402)

In [52]:
df1.to_csv(other, index=False)

In [60]:
cols = [ "Coil Current C1 (A)",       
"Coil Current C2 (A)"         ,
"Coil Current C3 (A)"         ,
"Coil Current C4 (A)"         ,
"Coil Current C5 (A)"         ,
"Coil Current C6 (A)"         ,
"Contact Travel T1 (mm)"        ,
"Contact Travel T2 (mm)"        ,
"Contact Travel T3 (mm)"       , 
"Contact Travel T4 (mm)"      ,
"Contact Travel T5 (mm)"        ,
"Contact Travel T6 (mm)"        ,
"DCRM Res CH1 in uOhm"          ,
"DCRM Current CH1 in Amp"       ,
"CH1 Close-Velocity (m/s)"     , 
"CH1 Open-Velocity (m/s)"     ,
"CH1 Test Run"                  ,
"DCRM Res CH2 in uOhm"         , 
"DCRM Current CH2 in Amp"      , 
"CH2 Close-Velocity (m/s)"    ,  
"CH2 Open-Velocity (m/s)"     ,
"CH2 Test Run"                ,
"DCRM Res CH3 in uOhm"        ,
"DCRM Current CH3 in Amp"     ,
"CH3 Close-Velocity (m/s)"    ,
"CH3 Open-Velocity (m/s)"     ,
"CH3 Test Run"                  ,
"CH3 Resistance Break"         , 
"DCRM Res CH4 in uOhm"        ,
"DCRM Current CH4 in Amp"     ,
"CH4 Close-Velocity (m/s)"    ,
"CH4 Open-Velocity (m/s)"     ,
"CH4 Test Run"                ,
"CH4 Resistance Break"       , 
"DCRM Res CH5 in uOhm"      ,  
"DCRM Current CH5 in Amp"  ,   
"CH5 Close-Velocity (m/s)",    
"CH5 Open-Velocity (m/s)",     
"CH5 Test Run"                 ,
"DCRM Res CH6 in uOhm"        ,
"DCRM Current CH6 in Amp"    , 
"CH6 Close-Velocity (m/s)"  ,  
"CH6 Open-Velocity (m/s)"  ,   
"CH6 Test Run"            ,    
"CH3 Bounce Break"       ,     
"CH4 Bounce Break"      ,      
"CH1 Resistance Break" ,       
"CH2 Resistance Break",        
"CH1 Bounce Break",            
"CH2 Bounce Break"]
    
list(set(cols) - set(df1.columns)),list(set(df1.columns) - set(cols)),list(df1.columns) == cols

([], ['breaker_id', 'phase'], False)

In [61]:
for i, (c1, c2) in enumerate(zip(df1.columns, cols)):
    if c1 != c2:
        print(f"Mismatch at index {i}: df1 has '{c1}' but expected '{c2}'")

Mismatch at index 44: df1 has 'phase' but expected 'CH3 Bounce Break'
Mismatch at index 45: df1 has 'breaker_id' but expected 'CH4 Bounce Break'
Mismatch at index 46: df1 has 'CH3 Bounce Break' but expected 'CH1 Resistance Break'
Mismatch at index 47: df1 has 'CH4 Bounce Break' but expected 'CH2 Resistance Break'
Mismatch at index 48: df1 has 'CH1 Resistance Break' but expected 'CH1 Bounce Break'
Mismatch at index 49: df1 has 'CH2 Resistance Break' but expected 'CH2 Bounce Break'

In [62]:
i = 0
for col in cols:
    i+=1
i

50

In [65]:
df1.drop(df.columns[44], axis=1, inplace=True)

In [66]:
df1.drop(df.columns[45], axis=1, inplace=True)

In [67]:
df1.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,DCRM Current CH6 in Amp,CH6 Close-Velocity (m/s),CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0,0,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN

In [69]:
df1['breaker_id'] = 402
df1['phase'] = 'R'

In [70]:
df1.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break,breaker_id,phase
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R

In [71]:
df1.to_csv(other)

In [73]:
meow = Path('..',"Dataset/processed_402_R_faulty.csv")
meow.exists()

True

In [75]:
dp = pd.read_csv(meow)
dp.head()

,Unnamed: 0,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),...,CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break,breaker_id,phase
0,0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
1,1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
2,2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
3,3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
4,4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R

In [76]:
dp.drop(dp.columns[0], axis=1, inplace=True)

In [77]:
dp.head()

,Coil Current C1 (A),Coil Current C2 (A),Coil Current C3 (A),Coil Current C4 (A),Coil Current C5 (A),Coil Current C6 (A),Contact Travel T1 (mm),Contact Travel T2 (mm),Contact Travel T3 (mm),Contact Travel T4 (mm),...,CH6 Open-Velocity (m/s),CH6 Test Run,CH3 Bounce Break,CH4 Bounce Break,CH1 Resistance Break,CH2 Resistance Break,CH1 Bounce Break,CH2 Bounce Break,breaker_id,phase
0,0.015,0.029,0.015,0.029,0.0,0.0,0,0,0,0.10,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
1,0.007,0.022,0.000,0.037,0.0,0.0,0,0,0,-0.06,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
2,0.051,0.007,0.000,0.066,0.0,0.0,0,0,0,0.02,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
3,0.161,0.029,0.000,0.051,0.0,0.0,0,0,0,0.10,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R
4,0.286,0.022,0.015,0.029,0.0,0.0,0,0,0,0.18,...,0.12,TR4,NaN,NaN,NaN,NaN,NaN,NaN,402,R

In [78]:
dp['nan'].values_counts()

KeyError: 'nan'

In [79]:
dp.to_csv(meow, index=False)

In [80]:
dp.columns

Index(['Coil Current C1 (A)', 'Coil Current C2 (A)', 'Coil Current C3 (A)',
       'Coil Current C4 (A)', 'Coil Current C5 (A)', 'Coil Current C6 (A)',
       'Contact Travel T1 (mm)', 'Contact Travel T2 (mm)',
       'Contact Travel T3 (mm)', 'Contact Travel T4 (mm)',
       'Contact Travel T5 (mm)', 'Contact Travel T6 (mm)',
       'DCRM Res CH1 in uOhm', 'DCRM Current CH1 in Amp',
       'CH1 Close-Velocity (m/s)', 'CH1 Open-Velocity (m/s)', 'CH1 Test Run',
       'DCRM Res CH2 in uOhm', 'DCRM Current CH2 in Amp',
       'CH2 Close-Velocity (m/s)', 'CH2 Open-Velocity (m/s)', 'CH2 Test Run',
       'DCRM Res CH3 in uOhm', 'DCRM Current CH3 in Amp',
       'CH3 Close-Velocity (m/s)', 'CH3 Open-Velocity (m/s)', 'CH3 Test Run',
       'CH3 Resistance Break', 'DCRM Res CH4 in uOhm',
       'DCRM Current CH4 in Amp', 'CH4 Close-Velocity (m/s)',
       'CH4 Open-Velocity (m/s)', 'CH4 Test Run', 'CH4 Resistance Break',
       'DCRM Res CH5 in uOhm', 'DCRM Current CH5 in Amp',
       'CH5 Close-Velocity (m/s)', 'CH5 Open-Velocity (m/s)', 'CH5 Test Run',
       'DCRM Res CH6 in uOhm', 'DCRM Current CH6 in Amp',
       'CH6 Close-Velocity (m/s)', 'CH6 Open-Velocity (m/s)', 'CH6 Test Run',
       'CH3 Bounce Break', 'CH4 Bounce Break', 'CH1 Resistance Break',
       'CH2 Resistance Break', 'CH1 Bounce Break', 'CH2 Bounce Break',
       'breaker_id', 'phase'],
      dtype='str')

In [81]:
if 'Unknown' in dp.columns:
    print("Column 'Unknown' exists in the DataFrame.")